[tool.poetry]
name = "phish-setlist-pandas"
version = "0.0.3"
description = "ğŸ«š ğŸŒµ ğŸ¥ª â­•ï¸"
authors = ["Jared Wenerd <wenerd87@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
requests = "^2.32.5"
numpy = "^2.3.5"
pandas = "^2.3.3"
pysh-client = "^0.1.1"
ipython = "^9.7.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry"

[tool.autopep8]
max_line_length = 120
