[tool.poetry]
name = "phish-setlist-pandas"
version = "0.0.2"
description = "ğŸ«š ğŸŒµ ğŸ¥ª â­•ï¸"
authors = ["Jared Wenerd <wenerd87@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.20.0"
beautifulsoup4 = "*"
numpy = "*"
pandas = "*"
lxml = "*"
pysh-client = "^0.1.1"
ipython = "^8.29.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry"
